#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("COMP7211Assignment2.Droid.Resource", IsApplication=true)]

namespace COMP7211Assignment2.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int logo = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int wallpaper = 2130837505;
			
			// aapt resource value: 0x7F07005C
			public const int design_bottom_navigation_item_background = 2131165276;
			
			// aapt resource value: 0x7F07005D
			public const int design_fab_background = 2131165277;
			
			// aapt resource value: 0x7F07005E
			public const int design_ic_visibility = 2131165278;
			
			// aapt resource value: 0x7F07005F
			public const int design_ic_visibility_off = 2131165279;
			
			// aapt resource value: 0x7F070060
			public const int design_password_eye = 2131165280;
			
			// aapt resource value: 0x7F070061
			public const int design_snackbar_background = 2131165281;
			
			// aapt resource value: 0x7F070062
			public const int dislike1 = 2131165282;
			
			// aapt resource value: 0x7F070063
			public const int homeicon = 2131165283;
			
			// aapt resource value: 0x7F070064
			public const int ic_mtrl_chip_checked_black = 2131165284;
			
			// aapt resource value: 0x7F070065
			public const int ic_mtrl_chip_checked_circle = 2131165285;
			
			// aapt resource value: 0x7F070066
			public const int ic_mtrl_chip_close_circle = 2131165286;
			
			// aapt resource value: 0x7F070067
			public const int like1 = 2131165287;
			
			// aapt resource value: 0x7F070068
			public const int logo = 2131165288;
			
			// aapt resource value: 0x7F070069
			public const int mtrl_snackbar_background = 2131165289;
			
			// aapt resource value: 0x7F07006A
			public const int mtrl_tabs_default_indicator = 2131165290;
			
			// aapt resource value: 0x7F07006B
			public const int navigation_empty_icon = 2131165291;
			
			// aapt resource value: 0x7F07006C
			public const int newlogos = 2131165292;
			
			// aapt resource value: 0x7F07006D
			public const int notification_action_background = 2131165293;
			
			// aapt resource value: 0x7F07006E
			public const int notification_bg = 2131165294;
			
			// aapt resource value: 0x7F07006F
			public const int notification_bg_low = 2131165295;
			
			// aapt resource value: 0x7F070070
			public const int notification_bg_low_normal = 2131165296;
			
			// aapt resource value: 0x7F070071
			public const int notification_bg_low_pressed = 2131165297;
			
			// aapt resource value: 0x7F070072
			public const int notification_bg_normal = 2131165298;
			
			// aapt resource value: 0x7F070073
			public const int notification_bg_normal_pressed = 2131165299;
			
			// aapt resource value: 0x7F070074
			public const int notification_icon_background = 2131165300;
			
			// aapt resource value: 0x7F070075
			public const int notification_template_icon_bg = 2131165301;
			
			// aapt resource value: 0x7F070076
			public const int notification_template_icon_low_bg = 2131165302;
			
			// aapt resource value: 0x7F070077
			public const int notification_tile_bg = 2131165303;
			
			// aapt resource value: 0x7F070078
			public const int notify_panel_notification_icon_bg = 2131165304;
			
			// aapt resource value: 0x7F070079
			public const int tooltip_frame_dark = 2131165305;
			
			// aapt resource value: 0x7F07007A
			public const int tooltip_frame_light = 2131165306;
			
			// aapt resource value: 0x7F07007B
			public const int wallpaper = 2131165307;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F0C0000
			public const int dislike1 = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int homeicon = 2131492865;
			
			// aapt resource value: 0x7F0C0002
			public const int icon = 2131492866;
			
			// aapt resource value: 0x7F0C0003
			public const int icon_round = 2131492867;
			
			// aapt resource value: 0x7F0C0004
			public const int launcher_foreground = 2131492868;
			
			// aapt resource value: 0x7F0C0005
			public const int like1 = 2131492869;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppCompatDialogStyle = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int MainTheme = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int MainTheme_Base = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
